# Use the official image as a parent image.
FROM ubuntu:20.04

# Set the working directory.
WORKDIR /toolchain
# Copy the file from your host to your current location.
COPY package.json .

# Run the command inside your image filesystem.
RUN npm install
