#!/bin/bash
rsync -rzLR --safe-links \
pi@raspberrypi:/usr/include/ \
pi@raspberrypi:/lib/arm-linux-gnueabihf/libz.so.1 \
pi@raspberrypi:/lib/arm-linux-gnueabihf/libz.so.1.2.11 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libpng.so \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libpng16.so \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libpng16.so.16 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libpng16.so.16.36.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libasound.so \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libasound.so.2 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libasound.so.2.0.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libgtk-3.so \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libgtk-3.so.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libgtk-3.so.0.2404.1 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libfreetype.so \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libfreetype.so.6 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libfreetype.so.6.16.1 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libXinerama.so \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libXinerama.so.1 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libXinerama.so.1.0.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libXrandr.so \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libXrandr.so.2 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libXrandr.so.2.2.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libXcursor.so \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libXcursor.so.1 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libXcursor.so.1.0.2 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libglut.so \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libglut.so.3 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libglut.so.3.9.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libXcomposite.so \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libXcomposite.so.1 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libXcomposite.so.1.0.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libX11.so \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libX11.so.6 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libX11.so.6.3.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libxcb.so \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libxcb.so.1 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libxcb.so.1.1.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libXau.so \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libXau.so.6 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libXau.so.6.0.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libXdmcp.so \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libXdmcp.so.6 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libXdmcp.so.6.0.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libcurl.so \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libcurl.so \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libcurl.so.4 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libcurl.so.4.5.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libGL.so \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libGL.so.1 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libGL.so.1.7.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libglapi.so.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libglapi.so.0.0.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libGLdispatch.so.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libGLdispatch.so.0.0.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libGLX.so \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libGLX.so.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libGLX.so.0.0.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libGLX_indirect.so.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libGLX_mesa.so.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libGLX_mesa.so.0.0.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libbsd.so.0 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libbsd.so.0.9.1 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libwebkit2gtk-4.0.so \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libwebkit2gtk-4.0.so.37 \
pi@raspberrypi:/usr/lib/arm-linux-gnueabihf/libwebkit2gtk-4.0.so.37.44.5 ./
